-- AlterTable
ALTER TABLE "ModelSnapshot" ALTER COLUMN "yesAsk" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "noAsk" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Trade" ALTER COLUMN "entryPriceCts" SET DATA TYPE DOUBLE PRECISION;

